### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by davidbrochart** [asphalt-framework/asphalt-filewatcher#1]
The [documentation link](http://asphalt-filewatcher.readthedocs.org/en/latest/) is broken.

**Comment by agronholm** [comment]
This project has been dormant for a long time and is likely to be discontinued.

**Comment by davidbrochart** [comment]
Ah thanks for the feedback, anyway I didn't mean to post this issue here, but [there](https://github.com/asphalt-framework/asphalt-scheduling/issues/1).
