### ISSUE TITLE
Support for watchfiles

### ISSUE THREAD

**Issue by davidbrochart** [asphalt-framework/asphalt-filewatcher#2]
I don't know if it makes sense, since the goal of `asphalt-filewatcher` seems to provide an abstraction layer for various OS ([watchfiles](https://github.com/samuelcolvin/watchfiles) also abstracts OS out).

**Comment by agronholm** [comment]
I'm aware that there have been several such projects published since I wrote the code here.

**Comment by davidbrochart** [comment]
Thanks.
